name: .NET CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04

    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
          SA_PASSWORD: Your_password123
          ACCEPT_EULA: Y
        ports:
          - 1433:1433
        options: >-
          --health-cmd "exit 0"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Install sqlcmd tools
        run: |
          sudo rm -f /usr/share/keyrings/microsoft-prod.gpg /usr/share/keyrings/microsoft.gpg
          sudo rm -f /etc/apt/sources.list.d/mssql-release.list /etc/apt/sources.list.d/microsoft-prod.list
          sudo apt-get update
          sudo apt-get install -y curl apt-transport-https gnupg
          curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
          sudo install -o root -g root -m 644 microsoft.gpg /usr/share/keyrings/microsoft-prod.gpg
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft-prod.gpg] https://packages.microsoft.com/ubuntu/22.04/prod jammy main" | sudo tee /etc/apt/sources.list.d/mssql-release.list
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y mssql-tools unixodbc-dev
          echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> $GITHUB_ENV

      - name: Wait for SQL Server to be ready
        run: |
          for i in {1..60}; do
            if /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'Your_password123' -Q 'SELECT 1' > /dev/null 2>&1; then
              echo "SQL Server is up!"
              exit 0
            fi
            sleep 2
          done
          echo "SQL Server did not start in time" && exit 1

      - name: Restore dependencies
        run: dotnet restore Dynamiq.API/Dynamiq.API.sln

      - name: Build
        run: dotnet build Dynamiq.API/Dynamiq.API.sln --no-restore --configuration Release

      - name: Run tests
        env:
          ConnectionStrings__DefaultConnection: "Server=localhost,1433;Database=DynamiqDb;User Id=sa;Password=Your_password123;TrustServerCertificate=True;"
        run: dotnet test Dynamiq.API/Dynamiq.API.sln --no-build --configuration Release --verbosity normal

      - name: Show SQL Server logs on failure
        if: failure()
        run: |
          docker logs $(docker ps -a -q --filter ancestor=mcr.microsoft.com/mssql/server:2019-latest)
