name: .NET CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          SA_PASSWORD: "YourStrongPassword123!"
          ACCEPT_EULA: "Y"
        ports:
          - 1433:1433
        options: >-
          --health-cmd "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P YourStrongPassword123! -C -Q 'SELECT 1'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=20

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Wait for SQL Server to be ready
        run: |
          for i in {1..30}; do
            /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P YourStrongPassword123! -C -Q "SELECT 1" && break
            echo "Waiting for MSSQL..."
            sleep 2
          done

      - name: Restore dependencies
        run: dotnet restore Dynamiq.API/Dynamiq.Tests.slnf

      - name: Build
        run: dotnet build Dynamiq.API/Dynamiq.Tests.slnf --no-restore --configuration Release

      - name: Run tests
        env:
          ConnectionStrings__DefaultConnection: "Server=localhost,1433;Database=Dynamiq;User=sa;Password=YourStrongPassword123!;TrustServerCertificate=True"
        run: dotnet test Dynamiq.API/Dynamiq.Tests.slnf --no-build --configuration Release --logger trx
